# Avizo Project
# AvizoFire
# Generated by Avizo 8.1.1
remove -all
remove "physics.icol" "volrenWhite.am" "test.wrl" "GeometrySurface" "GeometrySurface.scanConverted" "GeometrySurface.Smt.SptGraph" "Display Open Inventor Scene" "Open Inventor Scene To Surface" "Surface View" "Scan Surface To Volume" "Volume Rendering Settings" "Volume Rendering" "Auto Skeleton" "Spatial Graph View" "Global Axes 2"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 65535

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/volrenWhite.am ] setLabel "volrenWhite.am"
"volrenWhite.am" setIconPosition 0 0
"volrenWhite.am" setNoRemoveAll 1
"volrenWhite.am" setVar "CustomHelp" {HxColormap256}
"volrenWhite.am" master disconnect
"volrenWhite.am" Datafield disconnect
"volrenWhite.am" fire
"volrenWhite.am" setMinMax 0 255
"volrenWhite.am" flags setValue 1
"volrenWhite.am" shift setMinMax -1 1
"volrenWhite.am" shift setButtons 0
"volrenWhite.am" shift setEditButton 1
"volrenWhite.am" shift setIncrement 0.133333
"volrenWhite.am" shift setValue 0
"volrenWhite.am" shift setSubMinMax -1 1
"volrenWhite.am" scale setMinMax 0 1
"volrenWhite.am" scale setButtons 0
"volrenWhite.am" scale setEditButton 1
"volrenWhite.am" scale setIncrement 0.1
"volrenWhite.am" scale setValue 1
"volrenWhite.am" scale setSubMinMax 0 1
"volrenWhite.am" fire
"volrenWhite.am" setViewerMask 65535

set hideNewModules 0
[ load ${SCRIPTDIR}/test.wrl ] setLabel "test.wrl"
"test.wrl" setIconPosition 20 10
"test.wrl" master disconnect
"test.wrl" fire
"test.wrl" fire
"test.wrl" setViewerMask 65535

set hideNewModules 0
create HxIvDisplay "Display Open Inventor Scene"
"Display Open Inventor Scene" setIconPosition 265 10
"Display Open Inventor Scene" setVar "CustomHelp" {HxIvDisplay}
"Display Open Inventor Scene" data connect "test.wrl"
"Display Open Inventor Scene" projection disconnect
"Display Open Inventor Scene" fire
"Display Open Inventor Scene" drawStyle setIndex 0 0
"Display Open Inventor Scene" fire
"Display Open Inventor Scene" setViewerMask 65534
"Display Open Inventor Scene" setShadowStyle 0
"Display Open Inventor Scene" setPickable 1

set hideNewModules 0
create HxGeometryToSurface "Open Inventor Scene To Surface"
"Open Inventor Scene To Surface" setIconPosition 160 40
"Open Inventor Scene To Surface" setVar "CustomHelp" {HxGeometryToSurface}
"Open Inventor Scene To Surface" data connect "test.wrl"
"Open Inventor Scene To Surface" fire
"Open Inventor Scene To Surface" tolerance setMinMax 0 0 1
"Open Inventor Scene To Surface" tolerance setValue 0 9.99999974737875e-06
"Open Inventor Scene To Surface" tolerance setMinMax 1 0 1
"Open Inventor Scene To Surface" tolerance setValue 1 0.100000001490116
"Open Inventor Scene To Surface" options setValue 0 0
"Open Inventor Scene To Surface" options setToggleVisible 0 1
"Open Inventor Scene To Surface" options setValue 1 0
"Open Inventor Scene To Surface" options setToggleVisible 1 1
"Open Inventor Scene To Surface" options setValue 2 0
"Open Inventor Scene To Surface" options setToggleVisible 2 1
"Open Inventor Scene To Surface" applyTransformToResult 1
"Open Inventor Scene To Surface" fire
"Open Inventor Scene To Surface" setViewerMask 65535
"Open Inventor Scene To Surface" setPickable 1

set hideNewModules 0
[ "Open Inventor Scene To Surface" action hit; "Open Inventor Scene To Surface" fire; "Open Inventor Scene To Surface" getResult
 ] setLabel "GeometrySurface"
"GeometrySurface" setIconPosition 21 70
"GeometrySurface" master connect "Open Inventor Scene To Surface"
"GeometrySurface" fire
"GeometrySurface" LevelOfDetail setMinMax -1 -1
"GeometrySurface" LevelOfDetail setButtons 1
"GeometrySurface" LevelOfDetail setEditButton 1
"GeometrySurface" LevelOfDetail setIncrement 1
"GeometrySurface" LevelOfDetail setValue -1
"GeometrySurface" LevelOfDetail setSubMinMax -1 -1
"GeometrySurface" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"GeometrySurface" fire
"GeometrySurface" setViewerMask 65535

set hideNewModules 0
create HxDisplaySurface "Surface View"
"Surface View" setIconPosition 356 70
"Surface View" setVar "CustomHelp" {HxDisplaySurface}
"Surface View" data connect "GeometrySurface"
"Surface View" colorField disconnect
"Surface View" colormap setDefaultColor 1 0.1 0.1
"Surface View" colormap setDefaultAlpha 0.500000
"Surface View" colormap setLocalRange 1
"Surface View" colormap setLocalMinMax 0.000000 1.000000
"Surface View" colormap enableAlpha 1
"Surface View" colormap enableAlphaToggle 0
"Surface View" colormap setAutoAdjustRangeMode 1
"Surface View" colormap setColorbarMinMax 0 1
"Surface View" colormap disconnect
"Surface View" Texture disconnect
"Surface View" ROI disconnect
"Surface View" projection disconnect
"Surface View" fire
"Surface View" drawStyle setValue 4
"Surface View" fire
"Surface View" drawStyle setSpecularLighting 1
"Surface View" drawStyle setTexture 1
"Surface View" drawStyle setAlphaMode 3
"Surface View" drawStyle setNormalBinding 0
"Surface View" drawStyle setSortingMode 1
"Surface View" drawStyle setLineWidth 0.000000
"Surface View" drawStyle setOutlineColor 0 0 0.2
"Surface View" textureWrap setIndex 0 1
"Surface View" cullingMode setValue 0
"Surface View" selectionMode setIndex 0 0
"Surface View" Patch setMinMax 0 1
"Surface View" Patch setButtons 1
"Surface View" Patch setEditButton 1
"Surface View" Patch setIncrement 1
"Surface View" Patch setValue 0
"Surface View" Patch setSubMinMax 0 1
"Surface View" BoundaryId setIndex 0 -1
"Surface View" materials setIndex 0 1
"Surface View" materials setIndex 1 0
"Surface View" colorMode setIndex 0 0
"Surface View" baseTrans setMinMax 0 1
"Surface View" baseTrans setButtons 0
"Surface View" baseTrans setEditButton 1
"Surface View" baseTrans setIncrement 0.1
"Surface View" baseTrans setValue 0.8
"Surface View" baseTrans setSubMinMax 0 1
"Surface View" VRMode setIndex 0 0
"Surface View" colorFieldMappingType setValue 0
"Surface View" setLighting 1
"Surface View" fire
"Surface View" hideBox 1
"Surface View" selectTriangles zab HIJMPLPPHPOIABAGIGPPPPABDHCBLFEL
"Surface View" fire
"Surface View" setViewerMask 65535
"Surface View" setShadowStyle 0
"Surface View" setPickable 1

set hideNewModules 0
create HxScanConvertSurface "Scan Surface To Volume"
"Scan Surface To Volume" setIconPosition 160 100
"Scan Surface To Volume" setVar "CustomHelp" {HxScanConvertSurface}
"Scan Surface To Volume" data connect "GeometrySurface"
"Scan Surface To Volume" field disconnect
"Scan Surface To Volume" fire
"Scan Surface To Volume" bbox setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"Scan Surface To Volume" bbox setValue 0 -1
"Scan Surface To Volume" bbox setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"Scan Surface To Volume" bbox setValue 1 4.75
"Scan Surface To Volume" bbox setMinMax 2 -3.40282346638529e+38 3.40282346638529e+38
"Scan Surface To Volume" bbox setValue 2 -1
"Scan Surface To Volume" bbox setMinMax 3 -3.40282346638529e+38 3.40282346638529e+38
"Scan Surface To Volume" bbox setValue 3 6.75
"Scan Surface To Volume" bbox setMinMax 4 -3.40282346638529e+38 3.40282346638529e+38
"Scan Surface To Volume" bbox setValue 4 -1
"Scan Surface To Volume" bbox setMinMax 5 -3.40282346638529e+38 3.40282346638529e+38
"Scan Surface To Volume" bbox setValue 5 6.75
"Scan Surface To Volume" dimensions setMinMax 0 -16777216 16777216
"Scan Surface To Volume" dimensions setValue 0 57
"Scan Surface To Volume" dimensions setMinMax 1 -16777216 16777216
"Scan Surface To Volume" dimensions setValue 1 77
"Scan Surface To Volume" dimensions setMinMax 2 -16777216 16777216
"Scan Surface To Volume" dimensions setValue 2 77
"Scan Surface To Volume" materials setIndex 0 0
"Scan Surface To Volume" options setValue 0 0
"Scan Surface To Volume" options setToggleVisible 0 1
"Scan Surface To Volume" applyTransformToResult 1
"Scan Surface To Volume" fire
"Scan Surface To Volume" setViewerMask 65535
"Scan Surface To Volume" setPickable 1

set hideNewModules 0
[ load ${SCRIPTDIR}/test-files/GeometrySurface.scanConverted ] setLabel "GeometrySurface.scanConverted"
"GeometrySurface.scanConverted" setIconPosition 20 130
"GeometrySurface.scanConverted" master connect "Scan Surface To Volume"
"GeometrySurface.scanConverted" sharedColormap setDefaultColor 0.8 0.8 0.8
"GeometrySurface.scanConverted" sharedColormap setDefaultAlpha 0.500000
"GeometrySurface.scanConverted" sharedColormap setLocalRange 1
"GeometrySurface.scanConverted" sharedColormap setLocalMinMax 0.000000 1.000000
"GeometrySurface.scanConverted" sharedColormap enableAlpha 1
"GeometrySurface.scanConverted" sharedColormap enableAlphaToggle 0
"GeometrySurface.scanConverted" sharedColormap setAutoAdjustRangeMode 1
"GeometrySurface.scanConverted" sharedColormap disconnect
"GeometrySurface.scanConverted" ImageData disconnect
"GeometrySurface.scanConverted" fire
"GeometrySurface.scanConverted" primary setIndex 0 0
"GeometrySurface.scanConverted" fire
"GeometrySurface.scanConverted" setViewerMask 65535

set hideNewModules 0
create HxVolumeRenderingSettings "Volume Rendering Settings"
"Volume Rendering Settings" setIconPosition 274 130
"Volume Rendering Settings" setVar "CustomHelp" {HxVolumeRenderingSettings}
"Volume Rendering Settings" data connect "GeometrySurface.scanConverted"
"Volume Rendering Settings" selectRoi disconnect
"Volume Rendering Settings" projection disconnect
"Volume Rendering Settings" fire
"Volume Rendering Settings" advancedSettings setValue 1
"Volume Rendering Settings" interpolation setValue 1
"Volume Rendering Settings" interpolationAdvanced setValue 0
"Volume Rendering Settings" composition setValue 0
"Volume Rendering Settings" quality setValue 1
"Volume Rendering Settings" options setValue 0 0
"Volume Rendering Settings" options setToggleVisible 0 1
"Volume Rendering Settings" options setValue 1 0
"Volume Rendering Settings" options setToggleVisible 1 1
"Volume Rendering Settings" lighting setState item 0 1 item 1 1 
"Volume Rendering Settings" gradient setState item 0 1 item 2 0.0001 
"Volume Rendering Settings" effects setValue 0 0
"Volume Rendering Settings" effects setToggleVisible 0 1
"Volume Rendering Settings" effects setValue 1 0
"Volume Rendering Settings" effects setToggleVisible 1 1
"Volume Rendering Settings" effects setValue 2 0
"Volume Rendering Settings" effects setToggleVisible 2 1
"Volume Rendering Settings" effects setValue 3 1
"Volume Rendering Settings" effects setToggleVisible 3 1
"Volume Rendering Settings" ambientOcclusion setValue 0 1
"Volume Rendering Settings" ambientOcclusion setToggleVisible 0 1
"Volume Rendering Settings" edgeEnhancement setState item 0 0 item 2 0.0001 
"Volume Rendering Settings" edge2D setState item 0 0 item 2 0.1 item 4 0.1 item 6 1 
"Volume Rendering Settings" boundaryOpacity setState item 0 0 item 2 2.5 item 4 2.5 
"Volume Rendering Settings" moveLowResolutionScale setMinMax 1 10
"Volume Rendering Settings" moveLowResolutionScale setButtons 1
"Volume Rendering Settings" moveLowResolutionScale setEditButton 1
"Volume Rendering Settings" moveLowResolutionScale setIncrement 1
"Volume Rendering Settings" moveLowResolutionScale setValue 3
"Volume Rendering Settings" moveLowResolutionScale setSubMinMax 1 10
"Volume Rendering Settings" samplingQuality setMinMax 0 1
"Volume Rendering Settings" samplingQuality setButtons 0
"Volume Rendering Settings" samplingQuality setEditButton 1
"Volume Rendering Settings" samplingQuality setIncrement 0.1
"Volume Rendering Settings" samplingQuality setValue 0.5
"Volume Rendering Settings" samplingQuality setSubMinMax 0 1
"Volume Rendering Settings" optimizations setValue 0 0
"Volume Rendering Settings" optimizations setToggleVisible 0 1
"Volume Rendering Settings" optimizations setValue 1 0
"Volume Rendering Settings" optimizations setToggleVisible 1 1
"Volume Rendering Settings" optimizations setValue 2 0
"Volume Rendering Settings" optimizations setToggleVisible 2 1
"Volume Rendering Settings" sliceAlignment setValue 2
"Volume Rendering Settings" projectionRefinement setMinMax 1 20
"Volume Rendering Settings" projectionRefinement setButtons 1
"Volume Rendering Settings" projectionRefinement setEditButton 1
"Volume Rendering Settings" projectionRefinement setIncrement 1
"Volume Rendering Settings" projectionRefinement setValue 3
"Volume Rendering Settings" projectionRefinement setSubMinMax 1 20
"Volume Rendering Settings" fire
"Volume Rendering Settings" setViewerMask 65534
"Volume Rendering Settings" setShadowStyle 0
"Volume Rendering Settings" setPickable 1

set hideNewModules 0
create HxVolumeRender2 "Volume Rendering"
"Volume Rendering" setIconPosition 274 150
"Volume Rendering" setVar "CustomHelp" {HxVolumeRender2}
"Volume Rendering" data connect "GeometrySurface.scanConverted"
"Volume Rendering" volumeRenderingSettings connect "Volume Rendering Settings"
"Volume Rendering" fire
"Volume Rendering" maskSelector disconnect
"Volume Rendering" colormap setDefaultColor 1 1 1
"Volume Rendering" colormap setDefaultAlpha 0.500000
"Volume Rendering" colormap setLocalRange 1
"Volume Rendering" colormap setLocalMinMax 0.000000 1.000000
"Volume Rendering" colormap enableAlpha 1
"Volume Rendering" colormap enableAlphaToggle 0
"Volume Rendering" colormap setAutoAdjustRangeMode 1
"Volume Rendering" colormap setColorbarMinMax 0 1
"Volume Rendering" colormap connect "volrenWhite.am"
"Volume Rendering" fire
"Volume Rendering" colormapLookup setValue 2
"Volume Rendering" gamma setMinMax 0.100000001490116 8
"Volume Rendering" gamma setButtons 0
"Volume Rendering" gamma setEditButton 1
"Volume Rendering" gamma setIncrement 0.526667
"Volume Rendering" gamma setValue 3
"Volume Rendering" gamma setSubMinMax 0.100000001490116 8
"Volume Rendering" alphaScale setMinMax 0 1
"Volume Rendering" alphaScale setButtons 0
"Volume Rendering" alphaScale setEditButton 1
"Volume Rendering" alphaScale setIncrement 0.1
"Volume Rendering" alphaScale setValue 1
"Volume Rendering" alphaScale setSubMinMax 0 1
"Volume Rendering" channelSelector setValue 0 1
"Volume Rendering" channelSelector setToggleVisible 0 1
"Volume Rendering" fire
"Volume Rendering" setViewerMask 65535
"Volume Rendering" setPickable 1

set hideNewModules 0
create HxExtAutoSkeleton "Auto Skeleton"
"Auto Skeleton" setIconPosition 160 180
"Auto Skeleton" setVar "CustomHelp" {HxExtAutoSkeleton}
"Auto Skeleton" data connect "GeometrySurface.scanConverted"
"Auto Skeleton" fire
"Auto Skeleton" Threshold setMinMax 0 1
"Auto Skeleton" Threshold setButtons 0
"Auto Skeleton" Threshold setEditButton 1
"Auto Skeleton" Threshold setIncrement 0.1
"Auto Skeleton" Threshold setValue 0
"Auto Skeleton" Threshold setSubMinMax 0 1
"Auto Skeleton" Preview setValue 0 0
"Auto Skeleton" Preview setToggleVisible 0 1
"Auto Skeleton" alpha setMinMax 0 1
"Auto Skeleton" alpha setButtons 0
"Auto Skeleton" alpha setEditButton 1
"Auto Skeleton" alpha setIncrement 0.1
"Auto Skeleton" alpha setValue 0.45
"Auto Skeleton" alpha setSubMinMax 0 1
"Auto Skeleton" param setMinMax 0 -16777216 16777216
"Auto Skeleton" param setValue 0 100
"Auto Skeleton" Options setValue 0 1
"Auto Skeleton" Options setToggleVisible 0 1
"Auto Skeleton" Options setValue 1 1
"Auto Skeleton" Options setToggleVisible 1 1
"Auto Skeleton" coefficients setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"Auto Skeleton" coefficients setValue 0 0.5
"Auto Skeleton" coefficients setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"Auto Skeleton" coefficients setValue 1 0.25
"Auto Skeleton" numberOfIterations setMinMax 0 -16777216 16777216
"Auto Skeleton" numberOfIterations setValue 0 10
"Auto Skeleton" ExposeObjects setValue 0 0
"Auto Skeleton" ExposeObjects setToggleVisible 0 1
"Auto Skeleton" ExposeObjects setValue 1 0
"Auto Skeleton" ExposeObjects setToggleVisible 1 1
"Auto Skeleton" ExposeObjects setValue 2 0
"Auto Skeleton" ExposeObjects setToggleVisible 2 1
"Auto Skeleton" DistanceMapOutput setState ""
"Auto Skeleton" ThinnedOutput setState ""
"Auto Skeleton" ThinnedTmpOutput setState ""
"Auto Skeleton" FilamentType setValue 0
"Auto Skeleton" applyTransformToResult 1
"Auto Skeleton" fire
"Auto Skeleton" setViewerMask 65535
"Auto Skeleton" setPickable 1

set hideNewModules 0
[ load ${SCRIPTDIR}/test-files/GeometrySurface.Smt.SptGraph ] setLabel "GeometrySurface.Smt.SptGraph"
"GeometrySurface.Smt.SptGraph" setIconPosition 20 210
"GeometrySurface.Smt.SptGraph" master connect "Auto Skeleton"
"GeometrySurface.Smt.SptGraph" fire
"GeometrySurface.Smt.SptGraph" fire
"GeometrySurface.Smt.SptGraph" setViewerMask 65535

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 321 210
"Spatial Graph View" data connect "GeometrySurface.Smt.SptGraph"
"Spatial Graph View" Statistics disconnect
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap setLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 0
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap setLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 0
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" fire
"Spatial Graph View" itemsToShow setValue 0 1
"Spatial Graph View" itemsToShow setToggleVisible 0 1
"Spatial Graph View" itemsToShow setValue 1 1
"Spatial Graph View" itemsToShow setToggleVisible 1 1
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" nodeScaleFactor setMinMax 0 10
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 0.666667
"Spatial Graph View" nodeScaleFactor setValue 0.0355437
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 10
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentStyle setValue 0 1
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 0
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 0
"Spatial Graph View" tubeScaleFactor setMinMax 0 10
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 0.666667
"Spatial Graph View" tubeScaleFactor setValue 0.2
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 10
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" setVisibility HIJMPLPPPPPPHPAAAJPKADPN HIJMPLPPPPPPHPAAAJPKADPN
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 65535
"Spatial Graph View" setPickable 1

set hideNewModules 0
create HxAxis "Global Axes 2"
"Global Axes 2" setIconPosition 50 292
"Global Axes 2" setVar "CustomHelp" {HxAxis}
"Global Axes 2" data disconnect
"Global Axes 2" fire
"Global Axes 2" axis setValue 0 1
"Global Axes 2" axis setToggleVisible 0 1
"Global Axes 2" axis setValue 1 1
"Global Axes 2" axis setToggleVisible 1 1
"Global Axes 2" axis setValue 2 1
"Global Axes 2" axis setToggleVisible 2 1
"Global Axes 2" options setValue 0 1
"Global Axes 2" options setToggleVisible 0 1
"Global Axes 2" options setValue 1 0
"Global Axes 2" options setToggleVisible 1 1
"Global Axes 2" options setValue 2 0
"Global Axes 2" options setToggleVisible 2 1
"Global Axes 2" thickness setMinMax 1 15
"Global Axes 2" thickness setButtons 0
"Global Axes 2" thickness setEditButton 1
"Global Axes 2" thickness setIncrement 0.933333
"Global Axes 2" thickness setValue 7.25882
"Global Axes 2" thickness setSubMinMax 1 15
"Global Axes 2" color setColor 0 1 0 0
"Global Axes 2" color setColor 1 0 1 0
"Global Axes 2" color setColor 2 0 0 1
"Global Axes 2" color setColor 3 1 0.8 0.5
"Global Axes 2" axisNames setState text 1 x text 3 y text 5 z 
"Global Axes 2" font setState name: "Arial Unicode MS" size: 10 buttonText: Select bold: 0 italic: 0 color: 0.8 0.8 0.8
"Global Axes 2" fire
"Global Axes 2" setBoundingBox 0 7.43951 0 7.43951 0 7.43951
"Global Axes 2" setDelta 0 
"Global Axes 2" setLocalMode 0 
"Global Axes 2" setFlip 0 0 
"Global Axes 2" setFlip 1 0 
"Global Axes 2" setFlip 2 0 
"Global Axes 2" fire
"Global Axes 2" setViewerMask 65535
"Global Axes 2" select
"Global Axes 2" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation -0.0193805 0.999585 -0.0213001 1.24002
viewer 0 setCameraPosition 19.4833 2.94862 8.92808
viewer 0 setCameraFocalDistance 18.6199
viewer 0 setCameraNearDistance 9.46743
viewer 0 setCameraFarDistance 22.6363
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

theObjectPool setSelectionOrder {Global Axes 2}
